# Site Info
title:              "skz's Blog"
description:        "A Blog"
author_name:        "Sasha Kuznetsov"
logo_url:           https://avatars.githubusercontent.com/u/11140296?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
# url:                https://heiswayi.github.io # main url
# baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressedg

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"